### ISSUE TITLE
Positional insert / updates

### ISSUE THREAD

**Issue by ghost** [MaikuB/incrementally_loading_listview#10]
I need to update rows in the list as new rows pushed to the app. 
But I need to not just add them at the bottom but rather in any previous location that I scrolled past.

The ops would be:
Insert
Update
Delete.

Thinking about how best to extend the code to support this.

The data coming in must know it's position. This is a sequence key unique to each table.

1. Just buffer all data on the client and so do the insert / update / delete into the buffer. The list then just reads from the buffer as the user scrolls up and down. This keeps the logic away from the list 

2. Maybe you have an idea on another approach

**Comment by MaikuB** [comment]
If by extending, you're referring to extending the widget I've implemented then I don't see why that is necessary. You may need to elaborate more on why you feel that is needed if that is what you meant. All the widget cares about is presenting what's in your data source and it does so by invoking the itemBuilder so that your app will need to return the widget that should be rendered in the app for a given index (see https://docs.flutter.io/flutter/widgets/IndexedWidgetBuilder.html). 

It's not really responsible for manipulating your data source beyond invoking a method that would be responsible to do so e.g. to load more items. The example app I've provided just depicts the most common scenario where items would appear at the bottom but this only because data source itself got updated so the items were appended. You could still do the operations you've described in your scenario instead if you wanted to. As an example, if you were to update the example app code I've written, you could replace [this line](https://github.com/MaikuB/incrementally_loading_listview/blob/30ddb2b5e495602c278b7b930c44a930116f41d5/example/lib/main.dart#L52) with `items.insert(i, Item('Item ${totalItems + i + 1}'));` and you'll see that the new items that got retrieved will appear at the top instead of the bottom
